server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 5
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 2

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers

  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
